// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package info.novatec.inspectit.cmr.service;

public final class AgentStorageService_Stub
    extends java.rmi.server.RemoteStub
    implements info.novatec.inspectit.cmr.service.IAgentStorageService
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_addDataObjects_0;
    
    static {
	try {
	    $method_addDataObjects_0 = info.novatec.inspectit.cmr.service.IAgentStorageService.class.getMethod("addDataObjects", new java.lang.Class[] {java.util.List.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public AgentStorageService_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of addDataObjects(List)
    public void addDataObjects(java.util.List $param_List_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_addDataObjects_0, new java.lang.Object[] {$param_List_1}, -6389782357919160904L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
